[package]
name = "chat_rust_app"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = "4.5.9"
fastrand = "2.1.0"
futures = "*"
tokio = { version = "1.38.0", features = ["full"] }
tokio-util = {version = "0.7.11", features=["full"]}
